### ISSUE TITLE
Encode is not thread safe

### ISSUE THREAD

**Issue by VirrageS** [vedhavyas/cuckoo-filter#12]
Shallow copy is not enough when doing encode. See that here: https://github.com/vedhavyas/cuckoo-filter/blob/master/cuckoo.go#L419 bucket array is only shallow copied. This means if we start encoding and do some delete keys concurrently we might have inconsistencies.

**Comment by vedhavyas** [comment]
Apologies for late reply. Should be fixed with the above PR and make a release after.
